### PR TITLE
Syncs mozjpeg.podspec

### PR DESCRIPTION
**Pull request by diegosanchezr**
Wraps transupp.h with extern C

Fixes: https://github.com/facebookincubator/spectrum/issues/26

### CODE REVIEW

**Comment by kornelski** [comment]
Change to a hardcoded tag from `:tag => "v#{spec.version}"` seems undesirable.

Also modification of source files looks hacky. Is `DONT_USE_EXTERN_C` essential here? Otherwise it looks like a standard pattern, and could probable be added to the `transupp.h` directly and perhaps even contributed to libjpeg-turbo upstream.

**Comment by cuva** [comment]
Hey @kornelski - thanks for your quick answer.

We guarded this with `DONT_USE_EXTERN_C` since this is also the pattern used in `jpeglib.h` - but happy to get rid of it if you think it's unnecessary.

> Change to a hardcoded tag from :tag => "v#{spec.version}" seems undesirable.

Agreed - this was the only way for use to push a new spec version without forcing a new version of `mozjpeg` - the plan is to drop that on the next release of `mozjpeg` when it gets back into sync with the podspec version. If you can think of a better alternative more than happy to hear it out!

> and could probable be added to the transupp.h directly and perhaps even contributed to libjpeg-turbo upstream.

We _assumed_ that it wasn't there for a reason and this allowed us to fix a long standing issue in Spectrum without being dependant on changes applied to dependant libraries - that being said if you think it's a reasonably thing to do I'm more than happy to submit a PR there and get rid of this hack in the podfile.

We've already pushed the spec 3.3.2 spec file to the central cocoapods spec repo to make sure it fixed our issues - but I think the changes you're suggested are reasonable.

Also, while we'll be keeping the spec up to date with new releases of `mozjpeg` - there may be a value for you to register as a co-owner of the pod as described in #310.

If anything, please let us know - thanks again.

**Comment by kornelski** [comment]
Oh, I didn't notice `DONT_USE_EXTERN_C` is already used in `jpeglib.h`. In that case it seems OK to stick with it.

Could you add these guards to `transupp.h` directly, without changing the spec file? I'll merge it then and make a patch for upstream.

**Comment by cuva** [comment]
Sure thing - @diegosanchezr will take care of it first thing next week! Thanks @kornelski - have an excellent weekend.

**Comment by diegosanchezr** [comment]
I'm abandoning this since the .podspec was already published and we'd need to point to the code with the fix in transupp.h. We'll get back to normal with the next release.

**Pull request closed without merging**
