### PR TITLE
Merge with new libjpeg-turbo repository

### LINKED ISSUE #202: Segfaults when compiled with LLVM/clang
Hi,

we have noticed that mozjpeg compiled with clang-3.8.0 causes many segfaults i.e. firefox, dolphin.
https://issues.openmandriva.org/show_bug.cgi?id=1560
https://issues.openmandriva.org/show_bug.cgi?id=1559

Sources for uour mozjpeg package can be found here https://github.com/OpenMandrivaAssociation/mozjpeg

### PR DESCRIPTION
**Pull request by pornel**
Brings mozjpeg up to date with libjpeg-turbo up to commit 346837cad3f5166d3d8ea8a65c9ba6eff97c59b0

Fixes #202

The large number of commits is due to bringing git history of the official libjpeg-turbo repo (the increase in repository size is not as big, because git stores all files' data only once). This will make merging of future changes from libjpeg-turbo easier, and obsoletes previous complicated git-svn workflow.

All unit tests pass, and all mozjpeg-optimized files [are the same](https://github.com/mozilla/mozjpeg/issues/202#issuecomment-217044061). A workaround is needed for the buffer size test to run in reasonable time #201, but this is not a new problem.

### CODE REVIEW

**Comment by pornel** [comment]
I've discussed this with @bdaehlie. The plan is to make a release once libjpeg-turbo 1.5 is out.

This brings commits up to libjpeg-turbo 1.4.2. It will make it easier to merge in libjpeg-turbo 1.5 once that is out, because the difference between branches will be smaller.

Incremental approach to merging may also help diagnose potential problems, because we'll have several merge commits along the way to bisect, so it'll be easier to investigate regressions than with just one massive merge.

**Comment by thisconnect** [comment]
Hi, is there an estimate when this is going to be released in?

**Comment by pornel** [comment]
When libjpeg-turbo 1.5 is released.

**Comment by CoolOppo** [comment]
@thisconnect I saw that you originally said "when this is going to be released in", and I came to this thread to see that you actually corrected it. For some reason, that made me pretty happy.

**Comment by thisconnect** [comment]
@pornel thanks! @CoolOppo little things matter :)

**Pull request merged**
