### PR TITLE
allow mozjpeg to be wrapped by other CMake projects

### PR DESCRIPTION
**Pull request by SSE4**
this is follow up on #290 & #289

summary of changes:
- replaced **CMAKE_BINARY_DIR** by **CMAKE_CURRENT_BINARY_DIR**
- replaced paths relative to **CMAKE_SOURCE_DIR** by paths relative to **CMAKE_CURRENT_SOURCE_DIR** 
- for `install PROGRAM `instructions, replaced **CMAKE_CURRENT_BINARY_DIR** by **TARGET_FILE** generator expression

/cc @solvingj

### CODE REVIEW

**Comment by kornelski** [comment]
Does that also apply to libjpeg-turbo? We would like to keep differences between MozJPEG and libjpeg-turbo to minimum.

**Comment by SSE4** [comment]
@kornelski I'll take a look at libjpeg-turbo
BTW, any specific reason why CMake is allowed only for Windows? it seems like libjpeg-turbo doesn't have such a restriction.

**Comment by kornelski** [comment]
CMake improvements are a very recent addition to libjpeg-turbo. We'll get them in the next release.

**Comment by kornelski** [comment]
I've noticed the libjpeg-turbo project has rewritten that file to the point we can't merge it. So I won't be accepting changes to our CMakeLists.txt, because we'll be deleting our version and replacing it with libjpeg-turbo's.

**Comment by SSE4** [comment]
yes, totally makes sense. it would be much easier to just borrow libjpeg-turbo's version, as file already diverged significantly.

**Pull request closed without merging**
