### PR TITLE
Use temporary pool for internal recompression

### LINKED ISSUE #201: Buffer size regression test very slow
The "Buffer size regression test" run by `tjunittest` is insanely slow compared to the same test in `libjpeg-turbo` making running `make test` as part of a packaging workflow unfeasible.

For comparison on libjpeg-turbo master `make tjquicktest` finishes in under 30 seconds, while on mozjpeg I'm already running for 25 minutes and it only progressed to the second of six subsampling tests in the first colorspace.

### PR DESCRIPTION
**Pull request by pornel**
Fixes #201 which is caused by extreme growth of "permanent" memory pool whenever image is compressed, caused by internal recompression swapping destination managers

This PR also cherry-picks fix for potential memory corruption from https://github.com/libjpeg-turbo/libjpeg-turbo/issues/78

### CODE REVIEW

**Comment by bdaehlie** [comment]
Thanks @pornel . Can you separate out the cherry-picked fix from libjpeg-turbo from your fixes on top of that? Would be good to review and merge those separately.

**Comment by bdaehlie** [comment]
Alternatively you could just not cherry-pick the fix and wait for the upcoming 1.5.0 merge.

**Comment by pornel** [comment]
Without that cherry-pick the commit would cause a merge conflict.

**Comment by pornel** [comment]
Rebased on top of 1.5.0

**Pull request merged**
